
export const thoughts = [
  { quote: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
  { quote: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
  { quote: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius" },
  { quote: "Everything you can imagine is real.", author: "Pablo Picasso" },
  { quote: "The secret of getting ahead is getting started.", author: "Mark Twain" },
  { quote: "The best time to plant a tree was 20 years ago. The second best time is now.", author: "Chinese Proverb" },
  { quote: "You miss 100% of the shots you don't take.", author: "Wayne Gretzky" },
  { quote: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
  { quote: "Act as if what you do makes a difference. It does.", author: "William James" },
  { quote: "Success is not final, failure is not fatal: it is the courage to continue that counts.", author: "Winston Churchill" },
  { quote: "What you get by achieving your goals is not as important as what you become by achieving your goals.", author: "Zig Ziglar" },
  { quote: "The only limit to our realization of tomorrow is our doubts of today.", author: "Franklin D. Roosevelt" },
  { quote: "We may encounter many defeats but we must not be defeated.", author: "Maya Angelou" },
  { quote: "The purpose of our lives is to be happy.", author: "Dalai Lama" },
  { quote: "Life is what happens when you're busy making other plans.", author: "John Lennon" },
  { quote: "Get busy living or get busy dying.", author: "Stephen King" },
  { quote: "You have within you right now, everything you need to deal with whatever the world can throw at you.", author: "Brian Tracy" },
  { quote: "The greatest glory in living lies not in never falling, but in rising every time we fall.", author: "Nelson Mandela" },
  { quote: "To live is the rarest thing in the world. Most people exist, that is all.", author: "Oscar Wilde" },
  { quote: "That which does not kill us makes us stronger.", author: "Friedrich Nietzsche" },
  { quote: "It is never too late to be what you might have been.", author: "George Eliot" },
  { quote: "For every minute you are angry you lose sixty seconds of happiness.", author: "Ralph Waldo Emerson" },
  { quote: "If you want to live a happy life, tie it to a goal, not to people or things.", author: "Albert Einstein" },
  { quote: "Not how long, but how well you have lived is the main thing.", author: "Seneca" },
  { quote: "If life were predictable it would cease to be life, and be without flavor.", author: "Eleanor Roosevelt" },
  { quote: "The whole secret of a successful life is to find out what is one's destiny to do, and then do it.", author: "Henry Ford" },
  { quote: "In order to write about life first you must live it.", author: "Ernest Hemingway" },
  { quote: "The big lesson in life, baby, is never be scared of anyone or anything.", author: "Frank Sinatra" },
  { quote: "Curiosity about life in all of its aspects, I think, is still the secret of great creative people.", author: "Leo Burnett" },
  { quote: "Life is not a problem to be solved, but a reality to be experienced.", author: "Soren Kierkegaard" },
  { quote: "The unexamined life is not worth living.", author: "Socrates" },
  { quote: "Turn your wounds into wisdom.", author: "Oprah Winfrey" },
  { quote: "The purpose of life is not to be happy. It is to be useful, to be honorable, to be compassionate, to have it make some difference that you have lived and lived well.", author: "Ralph Waldo Emerson" },
  { quote: "You will face many defeats in life, but never let yourself be defeated.", author: "Maya Angelou" },
  { quote: "The greatest pleasure of life is love.", author: "Euripides" },
  { quote: "Life is what we make it, always has been, always will be.", author: "Grandma Moses" },
  { quote: "Life is like riding a bicycle. To keep your balance, you must keep moving.", author: "Albert Einstein" },
  { quote: "The most important thing is to enjoy your life—to be happy—it's all that matters.", author: "Audrey Hepburn" },
  { quote: "I have found that if you love life, life will love you back.", author: "Arthur Rubinstein" },
  { quote: "We are all in the gutter, but some of us are looking at the stars.", author: "Oscar Wilde" },
  { quote: "Keep smiling, because life is a beautiful thing and there's so much to smile about.", author: "Marilyn Monroe" },
  { quote: "In three words I can sum up everything I've learned about life: it goes on.", author: "Robert Frost" },
  { quote: "Love the life you live. Live the life you love.", author: "Bob Marley" },
  { quote: "Life is either a daring adventure or nothing at all.", author: "Helen Keller" },
  { quote: "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.", author: "Ralph Waldo Emerson" },
  { quote: "It is our choices, Harry, that show what we truly are, far more than our abilities.", author: "J.K. Rowling" },
  { quote: "All the world's a stage, and all the men and women merely players.", author: "William Shakespeare" },
  { quote: "Your time is limited, so don't waste it living someone else's life.", author: "Steve Jobs" },
  { quote: "The only impossible journey is the one you never begin.", author: "Tony Robbins" },
  { quote: "In this life we cannot do great things. We can only do small things with great love.", author: "Mother Teresa" },
  { quote: "Only a life lived for others is a life worthwhile.", author: "Albert Einstein" },
  { quote: "The purpose of human life is to serve, and to show compassion and the will to help others.", author: "Albert Schweitzer" },
  { quote: "The biggest adventure you can take is to live the life of your dreams.", author: "Oprah Winfrey" },
  { quote: "Go confidently in the direction of your dreams! Live the life you've imagined.", author: "Henry David Thoreau" },
  { quote: "Do not go where the path may lead, go instead where there is no path and leave a trail.", author: "Ralph Waldo Emerson" },
  { quote: "I'm the one that's got to die when it's time for me to die, so let me live my life the way I want to.", author: "Jimi Hendrix" },
  { quote: "Don't cry because it's over, smile because it happened.", author: "Dr. Seuss" },
  { quote: "A life spent making mistakes is not only more honorable, but more useful than a life spent doing nothing.", author: "George Bernard Shaw" },
  { quote: "He who has a why to live can bear almost any how.", author: "Friedrich Nietzsche" },
  { quote: "The aim of life is to live, and to live means to be aware, joyously, drunkenly, serenely, divinely aware.", author: "Henry Miller" },
  { quote: "Sing like no one's listening, love like you've never been hurt, dance like nobody's watching, and live like it's heaven on earth.", author: "Mark Twain" },
  { quote: "The best way to predict your future is to create it.", author: "Abraham Lincoln" },
  { quote: "Life is a flower of which love is the honey.", author: "Victor Hugo" },
  { quote: "Do not take life too seriously. You will never get out of it alive.", author: "Elbert Hubbard" },
  { quote: "Keep your eyes on the stars and your feet on the ground.", author: "Theodore Roosevelt" },
  { quote: "The good life is one inspired by love and guided by knowledge.", author: "Bertrand Russell" },
  { quote: "You only live once, but if you do it right, once is enough.", author: "Mae West" },
  { quote: "I may not have gone where I intended to go, but I think I have ended up where I needed to be.", author: "Douglas Adams" },
  { quote: "Life isn't about finding yourself. Life is about creating yourself.", author: "George Bernard Shaw" },
  { quote: "Life is a long lesson in humility.", author: "James M. Barrie" },
  { quote: "The journey of a thousand miles begins with a single step.", author: "Lao Tzu" },
  { quote: "That's one small step for a man, one giant leap for mankind.", author: "Neil Armstrong" },
  { quote: "The trick in life is learning how to deal with it.", author: "Helen Mirren" },
  { quote: "A man who dares to waste one hour of time has not discovered the value of life.", author: "Charles Darwin" },
  { quote: "If you want to be happy, be.", author: "Leo Tolstoy" },
  { quote: "Life is a series of natural and spontaneous changes. Don't resist them; that only creates sorrow. Let reality be reality.", author: "Lao Tzu" },
  { quote: "Life is short, and it is up to you to make it sweet.", author: "Sarah Louise Delany" },
  { quote: "Every strike brings me closer to the next home run.", author: "Babe Ruth" },
  { quote: "I can't change the direction of the wind, but I can adjust my sails to always reach my destination.", author: "Jimmy Dean" },
  { quote: "What we think, we become.", author: "Buddha" },
  { quote: "The mind is everything. What you think you become.", author: "Buddha" },
  { quote: "An unexamined life is not worth living.", author: "Socrates" },
  { quote: "Eighty percent of success is showing up.", author: "Woody Allen" },
  { quote: "Your time is limited, don't waste it living someone else's life.", author: "Steve Jobs" },
  { quote: "Winning isn't everything, but wanting to win is.", author: "Vince Lombardi" },
  { quote: "I am not a product of my circumstances. I am a product of my decisions.", author: "Stephen Covey" },
  { quote: "Every child is an artist. The problem is how to remain an artist once he grows up.", author: "Pablo Picasso" },
  { quote: "You can never cross the ocean until you have the courage to lose sight of the shore.", author: "Christopher Columbus" },
  { quote: "I've learned that people will forget what you said, people will forget what you did, but people will never forget how you made them feel.", author: "Maya Angelou" },
  { quote: "Either you run the day, or the day runs you.", author: "Jim Rohn" },
  { quote: "Whether you think you can or you think you can't, you're right.", author: "Henry Ford" },
  { quote: "The two most important days in your life are the day you are born and the day you find out why.", author: "Mark Twain" },
  { quote: "Whatever you can do, or dream you can, begin it. Boldness has genius, power and magic in it.", author: "Johann Wolfgang von Goethe" },
  { quote: "The best revenge is massive success.", author: "Frank Sinatra" },
  { quote: "People often say that motivation doesn't last. Well, neither does bathing. That's why we recommend it daily.", author: "Zig Ziglar" },
  { quote: "Life shrinks or expands in proportion to one's courage.", author: "Anais Nin" },
  { quote: "If you hear a voice within you say ‘you cannot paint,’ then by all means paint and that voice will be silenced.", author: "Vincent Van Gogh" },
  { quote: "There is only one way to avoid criticism: do nothing, say nothing, and be nothing.", author: "Aristotle" },
  { quote: "The only person you are destined to become is the person you decide to be.", author: "Ralph Waldo Emerson" },
  { quote: "Go confidently in the direction of your dreams. Live the life you have imagined.", author: "Henry David Thoreau" },
  { quote: "Believe you can and you’re halfway there.", author: "Theodore Roosevelt" },
];
