[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"

[[plugins]]
<<<<<<< HEAD
  package = "@vercel/plugin-nextjs"
=======
  package = "@netlify/plugin-nextjs"
##############################################
# ✅ Force Correct MIME Type for Sitemaps
##############################################

[[headers]]
  for = "/sitemap*.xml"
  [headers.values]
    Content-Type = "application/xml"

[[headers]]
  for = "/main-sitemap*.xml"
  [headers.values]
    Content-Type = "application/xml"

[[headers]]
  for = "/robots.txt"
  [headers.values]
    Content-Type = "text/plain"


##############################################
# ✅ Redirect Any Rogue Sitemap URLs to Main One
##############################################

[[redirects]]
  from = "/sitemap_index.xml"
  to = "/sitemap.xml"
  status = 301

[[redirects]]
  from = "/sitemap-0.xml"
  to = "/sitemap.xml"
  status = 301

[[redirects]]
  from = "/server-sitemap.xml"
  to = "/sitemap.xml"
  status = 301

[[redirects]]
  from = "/main-sitemap.xml"
  to = "/sitemap.xml"
  status = 301
>>>>>>> da6367b9eb324990e455230d2ee2a4bcba7891e1
